### ISSUE TITLE
[imagenet_r.py] wrong md5

### ISSUE THREAD

**Issue by kotekjedi** [shift-happens-benchmark/icml-2022#84]
Running the imagenet_r.py example causes the following error:
```
Downloading https://people.eecs.berkeley.edu/~hendrycks/imagenet-r.tar to ../../../../test_data\imagenet_r\imagenet-r.tar
2191080448it [07:01, 5195316.09it/s]                                
Traceback (most recent call last):
  File "E:\git_projects\bethgelab\icml-2022\shifthappens\tasks\imagenet_r\imagenet_r.py", line 81, in <module>
    sh_benchmark.evaluate_model(ResNet18(device="cuda", max_batch_size=128), "../../../../test_data")
  File "E:\git_projects\bethgelab\icml-2022\shifthappens\benchmark.py", line 150, in evaluate_model
    task.setup()
  File "E:\git_projects\bethgelab\icml-2022\shifthappens\tasks\imagenet_r\imagenet_r.py", line 40, in setup
    sh_utils.download_and_extract_archive(
  File "E:\git_projects\bethgelab\icml-2022\shifthappens\utils.py", line 127, in download_and_extract_archive
    tv_utils.download_url(url, data_folder, filename, md5)
  File "C:\Python310\lib\site-packages\torchvision\datasets\utils.py", line 152, in download_url
    raise RuntimeError("File not found or corrupted.")
RuntimeError: File not found or corrupted.
```
I think there is a problem with the md5 checksum since if you open the archive without it (just passing `None` instead of `A61312130A589D0CA1A8FCA1F2BD3337`), it does not cause any error.

Should we change m5? Or did we copy this wrong from some repo?

**Comment by stes** [comment]
I get the following results with the provided files:

```bash
$ md5sum imagenet-r.tar 
a61312130a589d0ca1a8fca1f2bd3337  imagenet-r.tar

$ sha1sum imagenet-r.tar 
e7bca26c185e221cbcf37f3c053d7b53c0bc8d03  imagenet-r.tar

$ sha256sum imagenet-r.tar 
18c6bf493b39a0d975d48e587437f562caab9c52ae6327dcfa9dd8eb54aa1b52  imagenet-r.tar
```

>> since if you open the archive without it

Could we adapt the PR #85 to actually use the MD5Sum mentioned above?
